name: Docker CI
on:
  push:
    tags:
      - "*"
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
        run: npm i broken-link-checker
        run: npm install --global wpcheck
      - name: Install Redrun
        run: bun i redrun -g --no-save
      - name: NPM Install
        run: npm i
      - name: Lint
        run: redrun lint
      - name: Build
        id: build
        run: >
          redrun build

          echo "::set-output name=version::$(grep '"version":' package.json -m1 | cut -d\" -f4)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push base-image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            coderaiser/cloudcmd:latest
            coderaiser/cloudcmd:${{ steps.build.outputs.version }}
      - name: Build and push alpine-image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.alpine
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            coderaiser/cloudcmd:latest-alpine
            coderaiser/cloudcmd:${{ steps.build.outputs.version }}-alpine
